version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - 8080:80
    depends_on:
      - backend
    networks:
      - project

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=reminders_db
      - DB_USERNAME=root
      - DB_PASSWORD=
    depends_on:
      - mysql
    volumes:
      - ./backend:/var/www/backend
    networks:
      - project

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - 8081:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/backend
    depends_on:
      - frontend
      - backend
    networks:
      - project

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'reminders_db'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      # create a table with some test data
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - project

volumes:
  mysql_data:

networks:
  project:
