apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: project
spec:
  serviceName: "mysql"
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 33060
              name: mysql
          volumeMounts:
            - name: mysql-data
              mountPath: /data/db
          env:
            - name: MYSQL_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_INITDB_DATABASE
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
